### ISSUE TITLE
Size limit option

### ISSUE THREAD

**Issue by vsoch** [converged-computing/oras-csi#2]
> This restriction should only be enforced upon [manifest/index](https://github.com/oras-project/oras-go/blob/e8225cb1e125bd4c13d6b586ae6d862050c3fae2/content.go#L215), not the sif container blob.

Can I just unset this limit
> yes, it's an option which you can change in the [resolve option](https://github.com/oras-project/oras-go/blob/e8225cb1e125bd4c13d6b586ae6d862050c3fae2/content.go#L58)

https://github.com/oras-project/oras-go/blob/e8225cb1e125bd4c13d6b586ae6d862050c3fae2/content.go#L58u

**Comment by sajayantony** [comment]
Layers are expected to GBs and so this limit should not apply to blob. Curious to see where is this limit being hit. A large manifest will potentially be rejected by a registry.

**Comment by vsoch** [comment]
I'm not super familiar with the "copy" concept (I like push/pull better as a clear abstraction) but the error happened when I was using copy for a remote artifact that had one image.layer that was larger than this limit. The container in question (and the layer) are this one: https://github.com/orgs/converged-computing/packages/container/oras-csi-plugin/84643215?tag=latest. Basically changing the current container in the volumeAttributes to that URI should reproduce the error. I'll try to do it again to see if there is any change.

> A large manifest will potentially be rejected by a registry.

It could be, although in this case the "registry" is just the local filesystem right? I was wondering if maybe ORAS does a check to see if there is enough space for it, and maybe in this case there wasn't (I was testing in a minikube VM). Can definitely look into this more!

**Comment by vsoch** [comment]
okay figured this out.
